version: '3.4'


x-pipeline-volumes:
  &pipeline-volumes
    - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json
    - ~/.aws/credentials:/tmp/.aws-credentials
    - ./notebooks:/opt/airflow/applications_file_directory/notebooks
    - ./data_science_pipeline:/opt/airflow/data_science_pipeline
    - ./tests:/opt/airflow/tests


services:
  test-client:
    volumes: *pipeline-volumes

  data-hub-pipelines:
    volumes: *pipeline-volumes
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json
      - AWS_SHARED_CREDENTIALS_FILE=/tmp/.aws-credentials
      - PYTHONPATH=/home/airflow/.local/lib/python3.8/site-packages
    user: 0:0

  jupyter:
    environment:
      - NB_UID=${USER_ID}
      - NB_GID=${GROUP_ID}
      - GOOGLE_CLOUD_PROJECT=${DATA_SCIENCE_GOOGLE_CLOUD_PROJECT}
    volumes:
      - .:/home/jovyan/data-science-dags
      - ~/.config/gcloud:/home/jovyan/.config/gcloud
      - ~/.aws/credentials:/home/jovyan/.aws/credentials
  
  peerscout-api:
    volumes: 
      - ./peerscout_api:/app/api/peerscout_api
      - ~/.aws/credentials:/root/.aws/credentials
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      - DEPLOYMENT_ENV=staging
    ports:
      - "${DATA_SCIENCE_DAGS_PEERSCOUT_API_PORT}:8080"

  peerscout-api-dev:
    volumes: 
      - ./peerscout_api:/app/api/peerscout_api
      - ./tests_peerscout_api:/app/api/tests_peerscout_api
    environment: 
      - PEERSCOUT_API_URL=http://peerscout-api:8080/api/peerscout
