version: '3.4'


x-pipeline-volumes:
  &pipeline-volumes
    - ./credentials.json:/root/.config/gcloud/credentials.json
    - ~/.aws/credentials:/root/.aws/credentials

services:
  peerscout-api:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/credentials.json
    volumes: 
      - ~/.aws/credentials:/root/.aws/credentials
      - ./credentials.json:/root/credentials.json

  test-client:
    volumes: *pipeline-volumes
