version: '3.4'


x-airflow-volumes:
  &airflow-volumes
    - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json
    - ~/.aws/credentials:/usr/local/airflow/.aws/credentials
    - ./notebooks:/usr/local/airflow/applications_file_directory/notebooks
    - ./dags:/usr/local/airflow/dags
    - ./data_science_pipeline:/usr/local/airflow/data_science_pipeline


services:
  webserver:
    ports:
      - "${DATA_SCIENCE_DAGS_AIRFLOW_PORT}:8080"
    volumes: *airflow-volumes

  scheduler:
    volumes: *airflow-volumes

  dask-worker:
    environment:
      - DEPLOYMENT_ENV=${DATA_SCIENCE_DAGS_DEV_DATASET}
    volumes: *airflow-volumes

  test-client:
    volumes: *airflow-volumes

  jupyter:
    environment:
      - NB_UID=${USER_ID}
      - NB_GID=${GROUP_ID}
    volumes:
      - .:/home/jovyan/data-science-dags
      - ~/.config/gcloud:/home/jovyan/.config/gcloud
      - ~/.aws/credentials:/home/jovyan/.aws/credentials
