version: '3.4'


x-airflow-volumes:
  &airflow-volumes
    - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json
    - ~/.aws/credentials:/tmp/.aws-credentials
    - ./notebooks:/opt/airflow/applications_file_directory/notebooks
    - ./dags:/opt/airflow/dags
    - ./data_science_pipeline:/opt/airflow/data_science_pipeline


services:
  webserver:
    ports:
      - "${DATA_SCIENCE_DAGS_AIRFLOW_PORT}:8080"
    volumes: *airflow-volumes

  scheduler:
    volumes: *airflow-volumes

  dask-worker:
    environment:
      - DEPLOYMENT_ENV=dev
    volumes: *airflow-volumes

  test-client:
    volumes: *airflow-volumes

  jupyter:
    environment:
      - NB_UID=${USER_ID}
      - NB_GID=${GROUP_ID}
      - GOOGLE_CLOUD_PROJECT=${DATA_SCIENCE_GOOGLE_CLOUD_PROJECT}
    volumes:
      - .:/home/jovyan/data-science-dags
      - ~/.config/gcloud:/home/jovyan/.config/gcloud
      - ~/.aws/credentials:/home/jovyan/.aws/credentials
  
  peerscout-api:
    volumes: 
      - ./data_science_pipeline:/app/peerscout_api/data_science_pipeline