version: '3.4'


x-pipeline-volumes:
  &pipeline-volumes
    - ./credentials.json:/root/.config/gcloud/credentials.json
    - ~/.aws/credentials:/root/.aws/credentials

services:
  peerscout-api:
    environment:
      # because of there is no model in ci, we are using staging
      - DEPLOYMENT_ENV=staging
      - GOOGLE_APPLICATION_CREDENTIALS=/root/credentials.json
      - DATA_SCIENCE_STATE_PATH=${DATA_SCIENCE_STATE_PATH}
    volumes: 
      - ~/.aws/credentials:/root/.aws/credentials
      - ./credentials.json:/root/credentials.json

  test-client:
    volumes: *pipeline-volumes
