version: '3.4'

services:
  peerscout-api:
    environment:
      # because of there is no model in ci, we are using staging
      - DEPLOYMENT_ENV=staging
      - GOOGLE_APPLICATION_CREDENTIALS=/root/credentials.json
    volumes: 
      - ~/.aws/credentials:/root/.aws/credentials
      - ./credentials.json:/root/credentials.json
